### ISSUE TITLE
issues with MATLAB R2023b

### ISSUE THREAD

**Issue by janneshb** [mit-acl/deep_panther#5]
apart from [this issue](https://github.com/mit-acl/deep_panther/issues/3) I found the following issues with MATLAB R2023b:

**1.** In [MyCasadiClampedUniformSpline.m](https://github.com/mit-acl/deep_panther/blob/3731fecdeb8d96a8225ce45cccdbcd63adb9dfe7/panther/matlab/MyCasadiClampedUniformSpline.m#L85C1-L86C1) change

```
obj.getPosT=casadi.Function('f',{obj.t},{obj.expression});
```
to
```
options.allow_free = true;
obj.getPosT=casadi.Function('f',{obj.t},{obj.expression}, options);
```

**2.** In [main.m](https://github.com/mit-acl/deep_panther/blob/3731fecdeb8d96a8225ce45cccdbcd63adb9dfe7/panther/matlab/main.m#L664) change

```
my_func = opti.to_function('my_func', par_and_init_guess_exprs, results_expresion, par_and_init_guess_names, results_names);
```
to
```
options.allow_duplicate_io_names = true;
my_func = opti.to_function('my_func', par_and_init_guess_exprs, results_expresion, par_and_init_guess_names, results_names, options);
```

**Comment by jtorde** [comment]
This should be fixed in https://github.com/mit-acl/deep_panther/pull/6
